
SELECT EMPNO AS "#", ENAME AS "Name", JOB AS "Job", HIREDATE AS "Hire Date" FROM EMP ;


SELECT DISTINCT JOB AS "Job" FROM EMP ;


SELECT ENAME||', '||JOB AS "Employee and Title" FROM EMP ;


SELECT EMPNO||', '||ENAME||', '||JOB||', '||MGR||', '||HIREDATE||', '||SAL||', '||COMM||', '||DEPTNO AS "THE_OUTPUT" FROM EMP;


SELECT ENAME, JOB, HIREDATE FROM EMP WHERE HIREDATE BETWEEN '20-FEB-1981' AND '1-MAY-1981' ORDER BY HIREDATE ;


SELECT ENAME, DEPTNO FROM EMP WHERE DEPTNO IN (10,30) ORDER BY DEPTNO ;


SELECT ENAME AS "Employee", SAL	AS "Salary" FROM EMP WHERE SAL>'1500' AND DEPTNO IN (10,30) ;


SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE LIKE '%1982' ;


SELECT ENAME,JOB FROM EMP WHERE MGR IS NULL ;


SELECT ENAME, SAL, COMM FROM EMP WHERE COMM IS NOT NULL ORDER BY SAL, COMM DESC ;


SELECT ENAME FROM EMP WHERE (ENAME LIKE 'L%l%' OR ENAME LIKE '%l%l%') AND DEPTNO='30' OR MGR='7782' ;


SELECT ENAME, JOB, SAL FROM EMP WHERE JOB IN ('CLERK', 'ANALYST') AND ( SAL NOT IN (1000,3000,5000)) ;


SELECT ENAME, SAL, COMM FROM EMP WHERE (COMM>(SAL+(SAL/10)) ) ;
