DECLARE
	CURSOR GRATIS_CURS IS
	SELECT IDOB, TITLU, RATING, DATAO
	FROM OBIECT_ARTA 
	WHERE PRET=0;

	v_ID OBIECT_ARTA.IDOB%TYPE;
	v_TITLU OBIECT_ARTA.TITLU%TYPE;
	v_RATING OBIECT_ARTA.RATING%TYPE;
	v_DATA OBIECT_ARTA.DATAO%TYPE;
BEGIN
	OPEN GRATIS_CURS;
	LOOP
		FETCH GRATIS_CURS INTO v_ID, v_TITLU, v_RATING, v_DATA;
		EXIT WHEN GRATIS_CURS%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE(v_TITLU||' '||v_RATING||' '||v_DATA);
		
		INSERT INTO GRATIS
			VALUES(v_ID);
	END LOOP;
CLOSE GRATIS_CURS;
END;

/